apiVersion: v1
kind: List
items:
- apiVersion: config.gatekeeper.sh/v1alpha1
  kind: Config
  metadata:
    name: config
    namespace: gatekeeper-system
  spec:
    sync:
      syncOnly:
      - kind: PersistentVolumeClaim
        version: v1
